### PR TITLE
Standardize module

### PR DESCRIPTION
**Pull request by PeachScript**
Hi @patleeman , I'm using this plugin with `Vue.js`, I created an issue #11 before and fixed it with a PR #14, but the mirror repo has not been updated from upstream and the author did not have any response.

It is very unfriendly for developer, I mean the same project has multiple repo that need to maintain, so I created this PR to avoid this situation, include the following things:

1. Change module type to UMD, support `import` of ES6 and `require` of CommonJS;
2. Add `Quill` as a peer dependency in `package.json`;
3. Support register automatically if there has a global `Quill` variable;
4. Update example (remove register statement);
5. Update doc for `import` usage and remove mirror repo.

According to the contributing guide that you mentioned in the issue #11 , I will update the built assets after you review them.

Best regards.

### CODE REVIEW

**Comment by PeachScript** [comment]
@patleeman any idea?

**Comment by vishim** [comment]
Is this being looked at?

**Comment by patleeman** [comment]
Sorry for the late reply. I'll take a look at this PR. @PeachScript is it ready to go?

Thanks for the ping @vishim

**Comment by patleeman** [comment]
@PeachScript the changes LGTM. Thank you for taking the time to pull this together. Can you update the built assets and I'll merge it all in.

**Comment by PeachScript** [comment]
@patleeman you're welcome, assets has been updated.

**Comment by CosmoMyzrailGorynych** [comment]
Bump?

**Pull request merged**
